### ISSUE TITLE
Write elastix transformation files

### ISSUE THREAD

**Issue by tischi** [image-transform-converters/image-transform-converters#11]
@bogovicj @NicoKiaru 
Do we have anything to write a elastix transformation files that can be read by transformix?

For example, given an `AffineTransform3D` write the `Transformation.txt` file?

**Comment by bogovicj** [comment]
I image the transformix file would also need the output image size and pixel spacing correct?

**Comment by tischi** [comment]
Yes and I also wonder in what units the AffineTransform in the elastix file should be? Millimeters?

**Comment by tischi** [comment]
@NicoKiaru 

I just saw you did already something! Awesome!

https://github.com/image-transform-converters/image-transform-converters/blob/master/src/main/java/itc/transforms/elastix/ElastixTransform.java#L101

Is that useable?
Could you add an example into `/src/test` for using this to write an `ElastixAffineTransform` to a file?

**Comment by NicoKiaru** [comment]
Sure! Give me two hours. :-)

**Comment by tischi** [comment]
@NicoKiaru 
And the numbers in the AffineTransform, is their meaning: "From millimeter to millimeter"?

**Comment by NicoKiaru** [comment]
Can we create a gitter room ? I can't find where to do it ...

**Comment by NicoKiaru** [comment]
`And the numbers in the AffineTransform, is their meaning: "From millimeter to millimeter"?`

Humm.. I actually never handled physical units with elastix. So for me it's undefined, or rather pixels to pixels.

**Comment by NicoKiaru** [comment]
OK, done here : 
https://github.com/image-transform-converters/image-transform-converters/blob/master/src/test/java/itc/examples/ElastixTransformLoadAndSaveToFile.java

**Comment by tischi** [comment]
I tried it but it throws an error:
```
The elastix transform file is saved in the standard temporary directory : /var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/TransformParameters.4183402352837877576.txt
Exception in thread "main" java.lang.NullPointerException
	at itc.examples.ElastixTransformLoadAndSaveToFile.main(ElastixTransformLoadAndSaveToFile.java:23)
```

Do we really need the `.toFile()` method? Maybe `.save( path )` is enough?
(At least I do not really get what the `.toFile()` is doing... :)

**Comment by NicoKiaru** [comment]
Yeah, so I really find it super convenient because in the elastix wrapper I'm using, I need it to be a File, but I don't care where it's located. Also the file deleted when FIJI is exited. If you need to convert something but don't want to care with the file, and you want it to disappear after use, it's super convenient.

The error you get is line 23, so this line :
```
elastixTransform.CompressResultImage = !elastixTransform.CompressResultImage; // modifying a parameter of the transform
```

I suspect the field `CompressResultImage` is not initialized, which is weird because the text file 
https://github.com/image-transform-converters/image-transform-converters/blob/master/src/test/resources/elastix/TransformParameters.Affine3D.txt
Contains this field...

Did you open another transform file than this one ? Make sure it contains this field. Or just remove line 23, it's unnecessary in the test, it's just to show how to modify a parameter, but anybody could guess how to do that.

**Comment by NicoKiaru** [comment]
> I tried it but it throws an error:
> 
> ```
> The elastix transform file is saved in the standard temporary directory : /var/folders/91/6n93mtg108g6161n3sx_x33m0000gn/T/TransformParameters.4183402352837877576.txt
> Exception in thread "main" java.lang.NullPointerException
> 	at itc.examples.ElastixTransformLoadAndSaveToFile.main(ElastixTransformLoadAndSaveToFile.java:23)
> ```
> 
> Do we really need the `.toFile()` method? Maybe `.save( path )` is enough?
> (At least I do not really get what the `.toFile()` is doing... :)

Ok, I see, it's because of the public static String fields which are colliding with the way I use java reflection to store the file. I will make a fix.

**Comment by NicoKiaru** [comment]
Ok done.

**Comment by tischi** [comment]
Ok. I see, I broke it :-)
Thanks for the fix!
